service: sqs-lambda-for-laravel

provider:
    name: aws
    region: us-west-2
    stage: dev
    runtime: provided.al2
    iam:
      role: arn:aws:iam::169126896273:role/role-for-lambda
    environment:
      APP_ENV: local
      APP_DEBUG: true # set to false when moving to production
      APP_KEY: 'base64:WQUEgE4Jjbn4ixFeyxLFkYi03gYM4Kl6Q9WgzZpThh8='
      SQS_PREFIX: https://sqs.us-west-2.amazonaws.com/169126896273
      SQS_QUEUE: default-queue
      QUEUE_CONNECTION: sqs
      LOG_CHANNEL: stderr
      CACHE_DRIVER: array
      SESSION_DRIVER: array
    apiGateway:
      shouldStartNameWithService: true
    lambdaHashingVersion: 20201221

package:
    # Directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
        - '!.env'

functions:
    api:
      handler: public/index.php
      timeout: 28
      layers:
        - ${bref:layer.php-81-fpm}
      events:
        - httpApi: '*'
    defaultWorker:
      handler: worker.php
      layers:
        - ${bref:layer.php-81}
      environment:
        SQS_QUEUE: default-queue
      events:
        - sqs:
            arn: arn:aws:sqs:us-west-2:169126896273:default-queue
            batchSize: 1
    anotherWorker:
      handler: worker.php
      layers:
        - ${bref:layer.php-81}
      environment:
        SQS_QUEUE: another-queue
      events:
        - sqs:
            arn: arn:aws:sqs:us-west-2:169126896273:another-queue
            batchSize: 1

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
